config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'simple_pages/rules'
  root 'simple_pages#index'
  put 'games/:id/set_stone', to: 'games#set_stone'
  put 'games/:id/undo', to: 'games#undo'
  resources :games, only: [:index, :show, :create, :destroy]
  resources :scores
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>IshidoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
          crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css"
          integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg"
          crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
            integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
            integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
            crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="container-fluid">
      <nav id="my-navbar">
        <ul>
          <li>
            <a class="nav-brand" href="<%= root_path %>">ISHIDO</a>
          </li>
          <% if user_signed_in? %>
            <li> <%= link_to "Games", games_path %> </li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Login', new_user_session_path %></li>
            <li><%= link_to 'Sign up!', new_user_registration_path %></li>
          <% end %>
          <li>
            <%= link_to "Scores", scores_path %>
          </li>
          <li>
            <%= link_to "Rules", simple_pages_rules_path %>
          </li>
          <% if session[:current_game_name] %>
            <% if current_game = Game.find_by(name: session[:current_game_name]) %>
             <li>
               <%= link_to "Resume", game_path(current_game, name:current_game.name) %>
             </li>
            <% end %>
          <% end %>
          <li>
            <%= form_with(url: games_path, method: 'post', local: true, class: "inline-form")  do %>
              <%= submit_tag "New", name: "game[submit]" %>
            <% end %>
          </li>
        </ul>

      </nav>
      <div class="main">
        <%= yield  %>
        <p id="notice"><%= notice %></p>
        <p id="alert"><%= alert %></p>
      </div>
      <aside>
        <%= yield :aside %>
      </aside>
      <footer>
        &copy; 2018 IshidoApp
      </footer>
    </div><!-- end container-fluid -->
  </body>
</html>